language: go

go:
  - 1.13.x
  - 1.14.x

services:
  - docker

before_script:
  - git remote set-branches --add origin master
  - git fetch

script:
  - go build -a -o operator pkg/*.go
  - go test ./... -v -count=1
  - docker build --tag dmytrostriletskyi/stale-feature-branch-operator:$(cat .project-version) -f ops/Dockerfile .
  - ./ops/check-project-version.sh
