// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaleFeatureBranch) DeepCopyInto(out *StaleFeatureBranch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaleFeatureBranch.
func (in *StaleFeatureBranch) DeepCopy() *StaleFeatureBranch {
	if in == nil {
		return nil
	}
	out := new(StaleFeatureBranch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StaleFeatureBranch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaleFeatureBranchList) DeepCopyInto(out *StaleFeatureBranchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StaleFeatureBranch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaleFeatureBranchList.
func (in *StaleFeatureBranchList) DeepCopy() *StaleFeatureBranchList {
	if in == nil {
		return nil
	}
	out := new(StaleFeatureBranchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StaleFeatureBranchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaleFeatureBranchSpec) DeepCopyInto(out *StaleFeatureBranchSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaleFeatureBranchSpec.
func (in *StaleFeatureBranchSpec) DeepCopy() *StaleFeatureBranchSpec {
	if in == nil {
		return nil
	}
	out := new(StaleFeatureBranchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaleFeatureBranchStatus) DeepCopyInto(out *StaleFeatureBranchStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaleFeatureBranchStatus.
func (in *StaleFeatureBranchStatus) DeepCopy() *StaleFeatureBranchStatus {
	if in == nil {
		return nil
	}
	out := new(StaleFeatureBranchStatus)
	in.DeepCopyInto(out)
	return out
}
